POST http://localhost:3005/beers/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNiOGU2MzhlLTU2NmMtNGU5Yy04Y2ZmLWNlYWJjMGEwY2YyNCIsImlhdCI6MTczOTM2NjY5NSwiZXhwIjoxNzM5MzcwMjk1fQ.6JYBzQ51JqqOdnpbV6BtiptE7ErWL0dSQoYLjG1PwlY

{
	"name": "New Beer",
	"brewery": null,
	"description": "A cool beer",
	"style": "IPA",
	"ibu": "10",
	"abv": "6",
	"color": "golden"
}