DELETE http://localhost:3005/beers/7943258f-a8d4-4d8a-9b3d-b3377f6991bb HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNiOGU2MzhlLTU2NmMtNGU5Yy04Y2ZmLWNlYWJjMGEwY2YyNCIsImlhdCI6MTczODk5MjA5MiwiZXhwIjoxNzM4OTk1NjkyfQ.KXlpZ0nnAyuq-zORr0009bixj5FzsJlNWP8td8Ycn1M