### upload
PUT http://localhost:3005/breweries/144aed9b-cb5b-4155-a2f6-9f6ebc8833cc
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg4MDdhNmQwLTlkMGUtNDk0OS05MzczLTFiYWE0NGU3M2Q0OSIsImlhdCI6MTc1NTY5NzI5MiwiZXhwIjoxNzU1NzAwODkyfQ.FGV4QCynee5fsN6GrYcajxG2eXDKDGuZZKL5PhpO7Vk

--MyBoundary
Content-Disposition: form-data; name="beer_id"



--MyBoundary
Content-Disposition: form-data; name="location"

Chicago

--MyBoundary
Content-Disposition: form-data; name="date_of_founding"

2567

--MyBoundary
Content-Disposition: form-data; name="cover_image"; filename="yebisu24_can_350.png"
Content-Type: image/png

< ../../../Pictures/yebisu24_can_350.png

--MyBoundary--