PUT http://localhost:3005/stores/verified/02bc101b-a499-49e1-8b78-9988fe6a5755 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaXNwbGF5X25hbWUiOiJBZG1pblVzZXIiLCJpZCI6Ijg4MDdhNmQwLTlkMGUtNDk0OS05MzczLTFiYWE0NGU3M2Q0OSIsImlhdCI6MTc1MTgxMTI4NiwiZXhwIjoxNzUxODE0ODg2fQ.Xs8yzrGoPSGVp9nMBUrRZMRW2vizcXGpLTTkCfNNfzQ
